Repository fission-suite/fission, pull requests merged in 2019-10, with the labels that each got.

#117 CLI Watcher
  fission-cli/Main.hs
  fission-web-api.cabal
  library/Fission/CLI.hs
  library/Fission/CLI/Auth.hs
  library/Fission/CLI/Command/Login.hs
  library/Fission/CLI/Command/Up.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Config/Types.hs
  library/Fission/CLI/Display/Cursor.hs
  library/Fission/CLI/Display/Error.hs
  library/Fission/CLI/Display/Loader.hs
  library/Fission/CLI/Display/Success.hs
  library/Fission/CLI/Display/Wait.hs
  library/Fission/CLI/Login.hs
  library/Fission/CLI/Pin.hs
  library/Fission/CLI/Up.hs
  library/Fission/Emoji.hs
  library/Fission/Environment.hs
  library/Fission/IPFS/Peer.hs
  library/Fission/IPFS/Peer/Error.hs
  library/Fission/IPFS/Peer/Types.hs
  library/Fission/Internal/Applicative.hs
  library/Fission/Internal/UTF8.hs
  library/Fission/Storage/IPFS.hs
  library/Fission/Storage/PostgreSQL/Migrate.hs
  library/Fission/Time.hs
  library/Fission/Web/Error.hs
  library/Fission/Web/Heroku.hs
  package.yaml
  test/lint/Main.hs
Labels: 🐛 bug, 👩‍💻👨‍💻 DX, 💗 enhancement, 🚀 release

#118 Update readme and other small changes
  .github/CODE_OF_CONDUCT.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  ISSUE_TEMPLATE.md
  README.md
  example-config/addon-manifest.json.example
  example-config/env.yaml.example
  fission-web-api.cabal
  package.yaml
Labels: 📚 docs

#125 Add /ipfs/peers route to API
  fission-web-api.cabal
  library/Fission/IPFS/Info/Types.hs
  library/Fission/IPFS/Peer.hs
  library/Fission/IPFS/Peer/Types.hs
  library/Fission/Internal/Orphanage/OctetStream.hs
  library/Fission/Platform/Heroku/Provision.hs
  library/Fission/User/Types.hs
  library/Fission/Web.hs
  library/Fission/Web/Heroku.hs
  library/Fission/Web/IPFS.hs
  library/Fission/Web/IPFS/Peer.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
Labels: 🎛️ config, 💗 enhancement

#122 add registration route
  fission-web-api.cabal
  library/Fission/CLI/Command/Login.hs
  library/Fission/Platform/Heroku/Provision.hs
  library/Fission/User/Mutate.hs
  library/Fission/User/Provision/Types.hs
  library/Fission/Web.hs
  library/Fission/Web/Auth/Client.hs
  library/Fission/Web/Heroku.hs
  library/Fission/Web/Routes.hs
  library/Fission/Web/Swagger/Complete.hs
  library/Fission/Web/Swagger/Docs.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Client.hs
  library/Fission/Web/User/Create.hs
  library/Fission/Web/User/Verify.hs
Labels: 💗 enhancement, 🚀 release

#123 Register cli
  fission-web-api.cabal
  library/Fission/CLI.hs
  library/Fission/CLI/Command/Register.hs
  library/Fission/Web/Routes.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Client.hs
Labels: 🎛️ config, 💗 enhancement

#126 Expand & combine Swagger docs
  fission-web-api.cabal
  library/Fission/CLI/Auth.hs
  library/Fission/CLI/Command/Register.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Display/Error.hs
  library/Fission/CLI/Display/Loader.hs
  library/Fission/CLI/Display/Success.hs
  library/Fission/Emoji.hs
  library/Fission/Environment/Types.hs
  library/Fission/File/Types.hs
  library/Fission/IPFS/BinPath/Types.hs
  library/Fission/IPFS/Info/Types.hs
  library/Fission/IPFS/Name/Types.hs
  library/Fission/IPFS/Path/Types.hs
  library/Fission/IPFS/Peer/Types.hs
  library/Fission/IPFS/SparseTree/Types.hs
  library/Fission/Internal/JSON.hs
  library/Fission/Internal/Orphanage/BaseUrl.hs
  library/Fission/Platform/Heroku/AddOn/Manifest.hs
  library/Fission/Platform/Heroku/Provision.hs
  library/Fission/Security/Types.hs
  library/Fission/User/CID/Types.hs
  library/Fission/User/Provision/Types.hs
  library/Fission/Web.hs
  library/Fission/Web/Heroku.hs
  library/Fission/Web/IPFS.hs
  library/Fission/Web/IPFS/Client.hs
  library/Fission/Web/Routes.hs
  library/Fission/Web/Swagger.hs
  library/Fission/Web/Swagger/Complete.hs
  library/Fission/Web/Swagger/Docs.hs
  library/Fission/Web/Swagger/Public.hs
  library/Fission/Web/Tls.hs
  library/Fission/Web/Types.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Client.hs
  library/Fission/Web/User/Create.hs
  package.yaml
Labels: 🐛 bug, 💗 enhancement, 📚 docs

#131 Route53 automation with PUT /dns/{cid}
  example-config/env.yaml.example
  fission-web/Main.hs
  library/Fission/AWS.hs
  library/Fission/AWS/DomainName/Types.hs
  library/Fission/AWS/Environment/Types.hs
  library/Fission/AWS/Route53.hs
  library/Fission/AWS/Types.hs
  library/Fission/AWS/Zone/Types.hs
  library/Fission/Config/Types.hs
  library/Fission/Environment/Types.hs
  library/Fission/Internal/UTF8.hs
  library/Fission/Web.hs
  library/Fission/Web/Auth/Types.hs
  library/Fission/Web/DNS.hs
  library/Fission/Web/Error.hs
  library/Fission/Web/Heroku.hs
  library/Fission/Web/IPFS/Peer.hs
  library/Fission/Web/Routes.hs
  library/Fission/Web/Types.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Client.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement, 🚀 release

#130 Development Helpers
  library/Fission/Config/Types.hs
  library/Fission/Internal/Development.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#151 Adjust AWS json to camelCase
  example-config/env.yaml.example
  fission-web/Main.hs
  library/Fission/Storage/Environment/Types.hs
Labels: ⚠️ high priority, 🎛️ config, 🐛 bug

#154 Exception helpers
  library/Fission/Internal/Exception.hs
  package.yaml
Labels: 💗 enhancement

#159 Ensure DNS info is displayed on watch
  library/Fission/CLI.hs
  library/Fission/CLI/Command/Watch.hs
  package.yaml
Labels: 🐛 bug, 🤖 CLI

#165 Set dns to point to splash on user register
  library/Fission/Web/User.hs
  library/Fission/Web/User/Create.hs
  package.yaml
Labels: ⚡ dns, 💗 enhancement

#169 add whoami cli command
  library/Fission/CLI.hs
  library/Fission/CLI/Auth.hs
  library/Fission/CLI/Command/Whoami.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#170 Fission CLI logout
  library/Fission/CLI.hs
  library/Fission/CLI/Auth.hs
  library/Fission/CLI/Command/Logout.hs
  library/Fission/CLI/Display/Error.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement, 🤖 CLI

#175 🚀 Live Reloading
  .gitignore
  Makefile
  README.md
  app/devel.hs
  fission-web/Main.hs
  library/Fission/Internal/Development.hs
  library/Fission/Web.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#176 Remove CLI
  README.md
  app/Main.hs
  fission-cli/Main.hs
  library/Fission/CLI.hs
  library/Fission/CLI/Auth.hs
  library/Fission/CLI/Command/Down.hs
  library/Fission/CLI/Command/Login.hs
  library/Fission/CLI/Command/Logout.hs
  library/Fission/CLI/Command/Register.hs
  library/Fission/CLI/Command/Up.hs
  library/Fission/CLI/Command/Up/Types.hs
  library/Fission/CLI/Command/Watch.hs
  library/Fission/CLI/Command/Watch/Types.hs
  library/Fission/CLI/Command/Whoami.hs
  library/Fission/CLI/Config/Types.hs
  library/Fission/CLI/DNS.hs
  library/Fission/CLI/Display/Cursor.hs
  library/Fission/CLI/Display/Error.hs
  library/Fission/CLI/Display/Loader.hs
  library/Fission/CLI/Display/Success.hs
  library/Fission/CLI/Display/Wait.hs
  library/Fission/CLI/Pin.hs
  package.yaml
  test/lint/Main.hs
Labels: 🤖 CLI

#177 Dont return data from register endpoint
  library/Fission/Web/Client.hs
  library/Fission/Web/Client/Request.hs
  library/Fission/Web/Client/Types.hs
  library/Fission/Web/IPFS/Client.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Client.hs
  library/Fission/Web/User/Create.hs
Labels: ⚠️ high priority, 🐛 bug

#178 Rename watch to dev, dev to build
  Makefile
  README.md
Labels: 👩‍💻👨‍💻 DX

#181 Fix #140: Heroku Deprovision 406
  library/Fission/Web/Heroku.hs
  library/Fission/Web/Log.hs
  library/Fission/Web/Server.hs
Labels: 🐛 bug, 🖥️ Heroku
