Repository fission-suite/fission, pull requests merged in 2019-12, with the labels that each got.

#220 Fix Swagger docs cURL generator & domain example
  library/Fission/AWS/DomainName/Types.hs
  library/Fission/Web.hs
  library/Fission/Web/Swagger.hs
  package.yaml
Labels: 🐛 bug, 📚 docs

#214 Remove streamly as it's unused
  package.yaml
Labels: 🐛 bug

#216 Move default fission peer to env var
  app/Fission/Environment/IPFS/Types.hs
  app/Fission/Internal/Development.hs
  app/Main.hs
  example-config/env.yaml.example
  library/Fission/Config/Types.hs
  library/Fission/IPFS/Peer.hs
  library/Fission/Platform/Heroku/Provision.hs
  library/Fission/Web.hs
  library/Fission/Web/IPFS.hs
  library/Fission/Web/IPFS/Peer.hs
Labels: 🎛️ config

#213 Fix Swagger Docs to allow for codegeneration
  library/Fission/File/Types.hs
  library/Fission/IPFS/CID/Types.hs
  library/Fission/IPFS/Peer/Types.hs
  library/Fission/IPFS/SparseTree/Types.hs
  library/Fission/Internal/Orphanage/MultipartForm.hs
  library/Fission/Platform/Heroku/Provision.hs
  library/Fission/Web/Swagger.hs
  library/Fission/Web/Types.hs
  library/Fission/Web/User/Password/Reset/Types.hs
Labels: 🔌 integration, 🚠 infrastructure

#215 Change RIO_VERBOSE -> DEBUG
  README.md
  app/Fission/Internal/Development.hs
  app/Fission/Storage/PostgreSQL.hs
  app/Main.hs
  library/Fission/App.hs
  library/Fission/Environment.hs
  test/coverage-code/Main.hs
  test/coverage-docs/Main.hs
Labels: 👩‍💻👨‍💻 DX

#223 Export set RIO verbose
  library/Fission/App.hs
Labels: 👩‍💻👨‍💻 DX

#212 Ipfs refactor
  app/Fission/Environment/IPFS/Types.hs
  app/Fission/Internal/Development.hs
  app/Fission/Internal/Orphanage/RIO.hs
  library/Fission/AWS/Route53.hs
  library/Fission/Config/Types.hs
  library/Fission/File/Types.hs
  library/Fission/IPFS/BinPath/Types.hs
  library/Fission/IPFS/CID/Types.hs
  library/Fission/IPFS/Client.hs
  library/Fission/IPFS/Client/Add.hs
  library/Fission/IPFS/Client/Cat.hs
  library/Fission/IPFS/Client/Param.hs
  library/Fission/IPFS/Client/Pin.hs
  library/Fission/IPFS/DAG/Link.hs
  library/Fission/IPFS/DAG/Link/Types.hs
  library/Fission/IPFS/DAG/Node/Types.hs
  library/Fission/IPFS/Error.hs
  library/Fission/IPFS/Gateway/Types.hs
  library/Fission/IPFS/Ignored/Types.hs
  library/Fission/IPFS/Info/Types.hs
  library/Fission/IPFS/Name/Types.hs
  library/Fission/IPFS/Path/Types.hs
  library/Fission/IPFS/Peer.hs
  library/Fission/IPFS/Peer/Error.hs
  library/Fission/IPFS/Peer/Types.hs
  library/Fission/IPFS/Process.hs
  library/Fission/IPFS/Process/Types.hs
  library/Fission/IPFS/SparseTree.hs
  library/Fission/IPFS/SparseTree/Types.hs
  library/Fission/IPFS/Stat.hs
  library/Fission/IPFS/Timeout/Types.hs
  library/Fission/IPFS/Types.hs
  library/Fission/IPFS/URL/Types.hs
  library/Fission/Internal/Orphanage/Natural.hs
  library/Fission/Platform/Heroku/Provision.hs
  library/Fission/Storage/IPFS/Add.hs
  library/Fission/Storage/IPFS/DAG.hs
  library/Fission/Storage/IPFS/Get.hs
  library/Fission/Storage/IPFS/Pin.hs
  library/Fission/User/CID/Mutation.hs
  library/Fission/Web.hs
  library/Fission/Web/DNS.hs
  library/Fission/Web/DNS/Client.hs
  library/Fission/Web/Error.hs
  library/Fission/Web/Heroku.hs
  library/Fission/Web/IPFS.hs
  library/Fission/Web/IPFS/CID.hs
  library/Fission/Web/IPFS/DAG.hs
  library/Fission/Web/IPFS/Download.hs
  library/Fission/Web/IPFS/Peer.hs
  library/Fission/Web/IPFS/Pin.hs
  library/Fission/Web/IPFS/Upload.hs
  library/Fission/Web/IPFS/Upload/Multipart.hs
  library/Fission/Web/IPFS/Upload/Simple.hs
  library/Fission/Web/Types.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Create.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#224 Fix swagger docs (Update to latest ipfs-haskell)
  stack.yaml
  stack.yaml.lock
Labels: 🐛 bug, 👩‍💻👨‍💻 DX

#227 Update IPFS status codes
  library/Fission/Web/Error.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement

#229 69 alphanumber password
  library/Fission/Internal/URL.hs
  library/Fission/Random.hs
  library/Fission/User/Password.hs
  library/Fission/User/Security.hs
  library/Fission/Web/Heroku.hs
Labels: ⚠️ high priority, 🐛 bug

#230 Rename awsMock to route53Mock
  app/Fission/Environment/AWS/Types.hs
  app/Fission/Internal/Development.hs
  app/Main.hs
  example-config/env.yaml.example
  library/Fission/AWS/Route53.hs
  library/Fission/AWS/Types.hs
  library/Fission/Config/Types.hs
  library/Fission/Web.hs
  library/Fission/Web/DNS.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Create.hs
Labels: 👩‍💻👨‍💻 DX

#231 Improve IPFS Error message for our API consumers
  library/Fission/Web/Error.hs
  library/Fission/Web/Heroku/Deprovision.hs
  library/Fission/Web/IPFS.hs
  library/Fission/Web/IPFS/DAG.hs
  library/Fission/Web/IPFS/Pin.hs
  library/Fission/Web/IPFS/Upload.hs
  library/Fission/Web/IPFS/Upload/Multipart.hs
  library/Fission/Web/IPFS/Upload/Simple.hs
  stack.yaml
  stack.yaml.lock
Labels: 👩‍💻👨‍💻 DX

#235 Add destructive sql files
  library/Fission/Models.hs
  library/Fission/User/CID/Mutation.hs
  library/Fission/Web/Heroku/Deprovision.hs
  library/Fission/Web/IPFS/CID.hs
  library/Fission/Web/IPFS/Pin.hs
  sql/1576714308_selda_to_persistent.sql
  sql/README.md
Labels: 👩‍💻👨‍💻 DX

#233 Update Register to throw a 409 on unique conflict
  library/Fission/User/Mutation.hs
  library/Fission/User/Mutation/Error.hs
  library/Fission/Web/User/Create.hs
Labels: 🐛 bug, 👩‍💻👨‍💻 DX

#236 Make email required for register
  library/Fission/User/Registration/Types.hs
  library/Fission/Web/User/Create.hs
Labels: 💗 enhancement
