Repository fission-suite/fission, pull requests merged in 2019-11, with the labels that each got.

#189 Longer HTTP Timeout
  app/Main.hs
  library/Fission/Web/Log.hs
Labels: 🐇 quick, 🐛 bug

#193 Sentry Integration
  app/Main.hs
  library/Fission/Web/Environment/Types.hs
  library/Fission/Web/Log/Sentry.hs
  library/Fission/Web/Log/Sentry/DSN/Types.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
Labels: 🔌 integration, 🚠 infrastructure

#192 DNS Swagger Docs
  library/Fission/Web/Swagger.hs
Labels: 🐛 bug, 📚 docs

#194 Added POST /user/reset_password route
  library/Fission/User/Mutate.hs
  library/Fission/User/Password/Types.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Password/Reset.hs
Labels: 💗 enhancement

#206 Return s3 node on /ipfs/peers
  library/Fission/Web/IPFS/Peer.hs
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement, 🤖 CLI

#209 Recursive add with optional ignores
  library/Fission/IPFS/DAG/Link.hs
  library/Fission/IPFS/DAG/Link/Types.hs
  library/Fission/IPFS/DAG/Node/Types.hs
  library/Fission/IPFS/Ignored/Types.hs
  library/Fission/IPFS/Stat.hs
  library/Fission/IPFS/Types.hs
  library/Fission/Internal/Orphanage/Glob/Pattern.hs
  library/Fission/Storage/IPFS.hs
  library/Fission/Storage/IPFS/Add.hs
  library/Fission/Storage/IPFS/DAG.hs
  library/Fission/Storage/IPFS/Get.hs
  library/Fission/Web/IPFS/DAG.hs
  library/Fission/Web/IPFS/Download.hs
  library/Fission/Web/IPFS/Upload/Multipart.hs
  library/Fission/Web/IPFS/Upload/Simple.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
Labels: 👩‍💻👨‍💻 DX, 💗 enhancement, 🤖 CLI

#211 Gateway env
  app/Fission/Environment/IPFS/Types.hs
  app/Fission/Internal/Development.hs
  app/Main.hs
  example-config/env.yaml.example
  library/Fission/AWS.hs
  library/Fission/AWS/Route53.hs
  library/Fission/Config/Types.hs
  library/Fission/IPFS/Gateway/Types.hs
  library/Fission/IPFS/Types.hs
  library/Fission/Web.hs
  library/Fission/Web/DNS.hs
  library/Fission/Web/User.hs
  library/Fission/Web/User/Create.hs
Labels: ⚡ dns, 🎛️ config, 💗 enhancement
