Repository fission-suite/fission, pull requests merged in 2019-09, with the labels that each got.

#90 Pin to cluster
  app/Main.hs
  fission-web-api.cabal
  package.yaml
  src/Fission/Config/Types.hs
  src/Fission/IPFS/CID/Types.hs
  src/Fission/IPFS/Client.hs
  src/Fission/IPFS/Client/Add.hs
  src/Fission/IPFS/Client/Cat.hs
  src/Fission/IPFS/Client/Param.hs
  src/Fission/IPFS/Client/Pin.hs
  src/Fission/IPFS/Types.hs
  src/Fission/Internal/Orphanage.hs
  src/Fission/Storage/IPFS.hs
  src/Fission/Storage/IPFSClient.hs
  src/Fission/Web.hs
  src/Fission/Web/Client.hs
  src/Fission/Web/Heroku.hs
  src/Fission/Web/IPFS.hs
  src/Fission/Web/IPFS/Pin.hs
  src/Fission/Web/IPFS/Upload.hs
  src/Fission/Web/IPFS/Upload/Multipart.hs
  src/Fission/Web/IPFS/Upload/Simple.hs
  stack.yaml
  stack.yaml.lock
Labels: 💗 enhancement, 🚠 infrastructure

#106 add note about needing to install liblzma
  README.md
Labels: 💗 enhancement, 📚 docs

#105 fixing FromEnv instances & prod default for host
  fission-cli/Main.hs
  fission-web/Main.hs
  library/Fission/Environment.hs
  library/Fission/IPFS/Types.hs
  library/Fission/Storage/Types.hs
  library/Fission/Web/Types.hs
Labels: 🐛 bug

#107 added POST /ipfs/dag route for dag puts
  fission-web-api.cabal
  library/Fission/Storage/IPFS.hs
  library/Fission/Storage/IPFS/DAG.hs
  library/Fission/Storage/IPFS/Pin.hs
  library/Fission/Web/Heroku.hs
  library/Fission/Web/IPFS.hs
  library/Fission/Web/IPFS/Client.hs
  library/Fission/Web/IPFS/DAG.hs
  library/Fission/Web/IPFS/Pin.hs
  package.yaml
Labels: 💗 enhancement, 🚀 release

#112 Turn on Clang backend optimzations
  fission-web-api.cabal
  package.yaml
Labels: 🎛️ config

#113 SQLite -> PostgreSQL
  .gitignore
  env.yaml.example
  fission-web-api.cabal
  fission-web/Main.hs
  library/Fission/CLI/Auth.hs
  library/Fission/Config/Types.hs
  library/Fission/Environment/Types.hs
  library/Fission/IPFS/BinPath/Types.hs
  library/Fission/IPFS/Client/Pin.hs
  library/Fission/IPFS/Environment/Types.hs
  library/Fission/IPFS/Timeout/Types.hs
  library/Fission/IPFS/Types.hs
  library/Fission/IPFS/URL/Types.hs
  library/Fission/Internal/Orphanage/PGConnectInfo.hs
  library/Fission/Internal/Orphanage/RIO.hs
  library/Fission/Storage/Environment/Types.hs
  library/Fission/Storage/PostgreSQL.hs
  library/Fission/Storage/PostgreSQL/Migrate.hs
  library/Fission/Storage/SQLite.hs
  library/Fission/Storage/SQLite/Internal.hs
  library/Fission/Storage/Types.hs
  library/Fission/Web/Environment/Types.hs
  library/Fission/Web/Types.hs
  package.yaml
  web-api.sqlite.bk
Labels: 🎛️ config, 🐛 bug, 💎 robustness, 💗 enhancement, 🚀 release, 🚠 infrastructure
